kind = "api"
previewPath = "/api-ielts"
title = "IELTS API Server"
version = "1.0.0"
id = "artifacts/ielts-api"

[[services]]
localPort = 8082
name = "IELTS API Server"
paths = ["/api-ielts", "/app-ielts-intro"]

[services.development]
run = "pnpm --filter @workspace/ielts-api run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/ielts-api", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["node", "--enable-source-maps", "artifacts/ielts-api/dist/index.mjs"]

[services.production.run.env]
PORT = "8082"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api-ielts/healthz"
