// 20 A2-level Listening tests organized as 4 sections × 5 tests.
// Each test: title, transcript segments tagged with voice (alloy=male, nova=female),
// 8-10 questions covering MCQ, Matching, Note Completion, Sentence Completion, Short Answer.
// Each question stores canonical answer + acceptable variants.

export type Voice = "alloy" | "nova";

export interface Segment {
  voice: Voice;
  text: string;
}

export type QuestionType =
  | "mcq"
  | "matching"
  | "note_completion"
  | "sentence_completion"
  | "short_answer";

export interface MCQQuestion {
  id: string;
  type: "mcq";
  prompt: string;
  options: string[];
  answer: number;
}

export interface MatchingQuestion {
  id: string;
  type: "matching";
  prompt: string;
  items: string[];
  options: string[];
  answers: number[];
}

export interface CompletionQuestion {
  id: string;
  type: "note_completion" | "sentence_completion" | "short_answer";
  prompt: string;
  wordLimit: number;
  answer: string;
  acceptable: string[];
  context?: string;
}

export type Question = MCQQuestion | MatchingQuestion | CompletionQuestion;

export interface ListeningTest {
  id: string;
  sectionId: 1 | 2 | 3 | 4;
  title: string;
  description: string;
  segments: Segment[];
  questions: Question[];
}

export interface ListeningSection {
  id: 1 | 2 | 3 | 4;
  title: string;
  description: string;
}

export const SECTIONS: ListeningSection[] = [
  { id: 1, title: "Section 1", description: "Everyday conversation between two people." },
  { id: 2, title: "Section 2", description: "A short monologue on an everyday topic." },
  { id: 3, title: "Section 3", description: "Conversation between 2–3 people in a simple educational context." },
  { id: 4, title: "Section 4", description: "A short academic monologue, simplified." },
];

// ---------------------------------------------------------------------------
// SECTION 1 — Everyday conversations
// ---------------------------------------------------------------------------

const S1_T1: ListeningTest = {
  id: "s1-t1",
  sectionId: 1,
  title: "Booking a hotel room",
  description: "Tom phones a small hotel to book a room.",
  segments: [
    { voice: "nova", text: "Good morning, Riverside Hotel. How can I help you?" },
    { voice: "alloy", text: "Hello. I would like to book a room for next weekend, please." },
    { voice: "nova", text: "Of course. What is your name?" },
    { voice: "alloy", text: "My name is Tom Wilson." },
    { voice: "nova", text: "Thank you, Tom. Which dates would you like?" },
    { voice: "alloy", text: "From Friday the fifteenth to Sunday the seventeenth. So, two nights." },
    { voice: "nova", text: "And do you want a single room or a double room?" },
    { voice: "alloy", text: "A double room, please. My wife is coming with me." },
    { voice: "nova", text: "We have a nice double room with a view of the river. It costs eighty-five pounds per night." },
    { voice: "alloy", text: "That sounds good. Does the price include breakfast?" },
    { voice: "nova", text: "Yes, breakfast is included. We serve it from seven to ten in the morning." },
    { voice: "alloy", text: "Perfect. Do you have free parking?" },
    { voice: "nova", text: "Yes, parking is free for hotel guests. Is there anything else you need?" },
    { voice: "alloy", text: "Yes, can I have a quiet room, please? I am a light sleeper." },
    { voice: "nova", text: "Of course. I will give you room two-oh-four. It is at the back of the hotel and very quiet." },
    { voice: "alloy", text: "Thank you. Can I pay when I arrive?" },
    { voice: "nova", text: "Yes, you can pay by card on arrival. Could I please have a phone number for the booking?" },
    { voice: "alloy", text: "Sure. It is oh seven nine, four five six, two one eight." },
    { voice: "nova", text: "Thank you, Tom. Your room is booked. We look forward to seeing you on Friday." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "How many nights does Tom want to stay?",
      options: ["One night", "Two nights", "Three nights", "A whole week"],
      answer: 1,
    },
    {
      id: "q2",
      type: "mcq",
      prompt: "What kind of room does Tom book?",
      options: ["A single room", "A double room", "A family room", "A twin room"],
      answer: 1,
    },
    {
      id: "q3",
      type: "note_completion",
      prompt: "The room costs ____ pounds per night.",
      wordLimit: 1,
      answer: "85",
      acceptable: ["85", "eighty-five", "eighty five"],
    },
    {
      id: "q4",
      type: "sentence_completion",
      prompt: "Breakfast is served from seven to ____ in the morning.",
      wordLimit: 1,
      answer: "ten",
      acceptable: ["ten", "10"],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "Why does Tom want a quiet room?",
      options: ["He is sick.", "He is a light sleeper.", "He is working.", "He has a baby."],
      answer: 1,
    },
    {
      id: "q6",
      type: "note_completion",
      prompt: "Room number: ____",
      wordLimit: 1,
      answer: "204",
      acceptable: ["204", "two hundred and four", "two-oh-four", "two oh four"],
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "What is included free for guests besides breakfast?",
      wordLimit: 1,
      answer: "parking",
      acceptable: ["parking", "the parking", "free parking"],
    },
    {
      id: "q8",
      type: "sentence_completion",
      prompt: "Tom can pay when he ____.",
      wordLimit: 2,
      answer: "arrives",
      acceptable: ["arrives", "arrive", "gets there", "checks in"],
    },
  ],
};

const S1_T2: ListeningTest = {
  id: "s1-t2",
  sectionId: 1,
  title: "At the gym reception",
  description: "Sarah asks about joining a local gym.",
  segments: [
    { voice: "alloy", text: "Hello, welcome to City Fitness. How can I help?" },
    { voice: "nova", text: "Hi, I would like some information about your gym, please." },
    { voice: "alloy", text: "Of course. Are you thinking of becoming a member?" },
    { voice: "nova", text: "Yes, I am. How much is the monthly fee?" },
    { voice: "alloy", text: "The standard membership is forty pounds a month. Students pay only thirty pounds." },
    { voice: "nova", text: "Oh good, I am a student. What does the membership include?" },
    { voice: "alloy", text: "It includes the gym, the swimming pool, and all group classes." },
    { voice: "nova", text: "What kind of classes do you have?" },
    { voice: "alloy", text: "We have yoga, spinning, dance, and boxing. Yoga is the most popular." },
    { voice: "nova", text: "When is the gym open?" },
    { voice: "alloy", text: "We open at six in the morning and close at ten at night, every day." },
    { voice: "nova", text: "Great. Do I need to bring anything for my first visit?" },
    { voice: "alloy", text: "Yes, please bring a clean towel and a water bottle. We sell water here too if you forget." },
    { voice: "nova", text: "Do I need to book the classes in advance?" },
    { voice: "alloy", text: "Yes. You should book on our website at least one day before the class." },
    { voice: "nova", text: "Okay. One more question — where is the changing room?" },
    { voice: "alloy", text: "It is on the first floor, next to the swimming pool. The lockers are free." },
    { voice: "nova", text: "Thank you very much. I will think about it and come back tomorrow." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "How much is the student membership per month?",
      options: ["£20", "£30", "£40", "£50"],
      answer: 1,
    },
    {
      id: "q2",
      type: "matching",
      prompt: "Match each item with the correct fact.",
      items: ["Most popular class", "Standard membership fee", "Closing time"],
      options: ["£40 a month", "Yoga", "10 pm", "£30 a month", "Spinning"],
      answers: [1, 0, 2],
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "The gym opens at ____ in the morning.",
      wordLimit: 1,
      answer: "six",
      acceptable: ["six", "6", "6am", "6 am"],
    },
    {
      id: "q4",
      type: "note_completion",
      prompt: "Bring a ____ and a water bottle.",
      wordLimit: 2,
      answer: "clean towel",
      acceptable: ["clean towel", "towel", "a towel", "a clean towel"],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "How should Sarah book a class?",
      options: ["By phone", "On the website", "By email", "In person at reception"],
      answer: 1,
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "Where is the changing room?",
      wordLimit: 2,
      answer: "first floor",
      acceptable: ["first floor", "the first floor", "on the first floor", "1st floor"],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "The lockers are ____.",
      wordLimit: 1,
      answer: "free",
      acceptable: ["free"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "When will Sarah come back?",
      options: ["Today", "Tomorrow", "Next week", "On the weekend"],
      answer: 1,
    },
  ],
};

const S1_T3: ListeningTest = {
  id: "s1-t3",
  sectionId: 1,
  title: "Ordering a pizza",
  description: "A man phones a pizza shop to make an order.",
  segments: [
    { voice: "nova", text: "Bella Pizza, good evening." },
    { voice: "alloy", text: "Hello. I would like to order a pizza, please." },
    { voice: "nova", text: "Sure. Is it for delivery or to collect?" },
    { voice: "alloy", text: "For delivery, please." },
    { voice: "nova", text: "What is your address?" },
    { voice: "alloy", text: "It is twelve Oak Road, flat number three." },
    { voice: "nova", text: "Twelve Oak Road. Got it. Which pizza would you like?" },
    { voice: "alloy", text: "I would like a large Margherita, please. Can I add mushrooms and olives?" },
    { voice: "nova", text: "Yes, of course. Each extra topping is one pound, so that is two pounds extra." },
    { voice: "alloy", text: "Okay. And can I have a bottle of cola too?" },
    { voice: "nova", text: "Sure. The total is fourteen pounds fifty." },
    { voice: "alloy", text: "How long will it take?" },
    { voice: "nova", text: "About thirty minutes. We are a bit busy tonight." },
    { voice: "alloy", text: "That is fine. Can I pay by card when the food arrives?" },
    { voice: "nova", text: "Yes, the driver will bring a card machine. What is your phone number, please?" },
    { voice: "alloy", text: "It is oh seven seven, two three four, eight nine one." },
    { voice: "nova", text: "Thank you. Your pizza will be there soon." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Is the order for delivery or collection?",
      options: ["Collection", "Delivery", "Eat in", "The customer is not sure."],
      answer: 1,
    },
    {
      id: "q2",
      type: "note_completion",
      prompt: "Address: 12 Oak Road, flat ____.",
      wordLimit: 1,
      answer: "3",
      acceptable: ["3", "three", "number 3", "no. 3"],
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "The man orders a large ____ pizza.",
      wordLimit: 1,
      answer: "Margherita",
      acceptable: ["margherita", "margarita"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match the item with the price.",
      items: ["One extra topping", "Total order"],
      options: ["£1", "£2", "£14.50", "£10"],
      answers: [0, 2],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "How long will the delivery take?",
      options: ["About 15 minutes", "About 20 minutes", "About 30 minutes", "About 45 minutes"],
      answer: 2,
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "How will the man pay?",
      wordLimit: 2,
      answer: "by card",
      acceptable: ["by card", "card", "with card", "with a card", "credit card"],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "The man also orders a bottle of ____.",
      wordLimit: 1,
      answer: "cola",
      acceptable: ["cola", "coke"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Why will the order take a bit longer?",
      options: ["The driver is far away.", "They are busy tonight.", "The pizza is large.", "The address is hard to find."],
      answer: 1,
    },
  ],
};

const S1_T4: ListeningTest = {
  id: "s1-t4",
  sectionId: 1,
  title: "Lost wallet at the cafe",
  description: "A woman reports a lost wallet at a small cafe.",
  segments: [
    { voice: "alloy", text: "Hello, can I help you?" },
    { voice: "nova", text: "Hi. I think I left my wallet here this morning." },
    { voice: "alloy", text: "Oh, I am sorry to hear that. Can you describe it?" },
    { voice: "nova", text: "Yes, it is a small brown leather wallet." },
    { voice: "alloy", text: "Were there any cards or money inside?" },
    { voice: "nova", text: "Yes, two bank cards, my driving licence, and about twenty pounds." },
    { voice: "alloy", text: "What time did you come to the cafe?" },
    { voice: "nova", text: "Around half past nine. I sat by the window and had a coffee and a muffin." },
    { voice: "alloy", text: "Let me check our lost property box. One moment please." },
    { voice: "alloy", text: "Yes! I found a brown wallet here. Is this one yours?" },
    { voice: "nova", text: "Oh, thank goodness! Yes, that is mine." },
    { voice: "alloy", text: "Could you please give me your full name and a phone number for our records?" },
    { voice: "nova", text: "Sure. My name is Anna Brown, and my number is oh seven nine, six three two, five four eight." },
    { voice: "alloy", text: "Thank you. Could you also sign this short form, please?" },
    { voice: "nova", text: "Of course. Thank you so much for your help." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "What did the woman lose?",
      options: ["A handbag", "A wallet", "A phone", "A set of keys"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "The wallet is small and made of ____ leather.",
      wordLimit: 1,
      answer: "brown",
      acceptable: ["brown"],
    },
    {
      id: "q3",
      type: "note_completion",
      prompt: "Inside the wallet: 2 bank cards, driving licence, and about £____.",
      wordLimit: 1,
      answer: "20",
      acceptable: ["20", "twenty"],
    },
    {
      id: "q4",
      type: "mcq",
      prompt: "What time did the woman come to the cafe?",
      options: ["Around 9:00", "Around 9:30", "Around 10:00", "Around 10:30"],
      answer: 1,
    },
    {
      id: "q5",
      type: "matching",
      prompt: "Match the woman with what she ordered or did.",
      items: ["Drink", "Food", "Place she sat"],
      options: ["Tea", "Coffee", "A muffin", "By the door", "By the window"],
      answers: [1, 2, 4],
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "What is the woman's full name?",
      wordLimit: 2,
      answer: "Anna Brown",
      acceptable: ["anna brown", "anna brown."],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "She must also sign a short ____.",
      wordLimit: 1,
      answer: "form",
      acceptable: ["form"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "How does the woman feel at the end?",
      options: ["Angry", "Worried", "Relieved and happy", "Confused"],
      answer: 2,
    },
  ],
};

const S1_T5: ListeningTest = {
  id: "s1-t5",
  sectionId: 1,
  title: "Choosing a holiday",
  description: "A couple talks to a travel agent about a short holiday.",
  segments: [
    { voice: "nova", text: "Good afternoon, welcome to Sunshine Travel. How can I help?" },
    { voice: "alloy", text: "Hello. My wife and I want to go on a short holiday next month." },
    { voice: "nova", text: "Lovely. Where would you like to go?" },
    { voice: "alloy", text: "We are not sure. We want somewhere warm but not too far." },
    { voice: "nova", text: "Have you thought about Spain or Portugal? They are both nice in May." },
    { voice: "alloy", text: "Spain sounds good. We like the food there." },
    { voice: "nova", text: "Great. How many nights would you like to stay?" },
    { voice: "alloy", text: "Five nights, please. From Monday to Saturday." },
    { voice: "nova", text: "I have a nice hotel in Barcelona, near the beach. It is one hundred and ten euros per night." },
    { voice: "alloy", text: "That is a bit much. Do you have something cheaper?" },
    { voice: "nova", text: "Yes, there is a smaller hotel in the city centre for ninety euros per night, with breakfast." },
    { voice: "alloy", text: "That is better. We will take that one." },
    { voice: "nova", text: "Wonderful. Do you want to book the flights too?" },
    { voice: "alloy", text: "Yes, please. We would like to fly in the morning if possible." },
    { voice: "nova", text: "There is a flight at ten thirty from Heathrow. Two return tickets are three hundred and twenty pounds in total." },
    { voice: "alloy", text: "Perfect. Let us book it. Do we need a visa for Spain?" },
    { voice: "nova", text: "No, you do not need a visa, but please bring your passport. Make sure it is valid for at least six months." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Where do the couple decide to go?",
      options: ["Portugal", "Spain", "Italy", "Greece"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "They will stay for ____ nights.",
      wordLimit: 1,
      answer: "five",
      acceptable: ["five", "5"],
    },
    {
      id: "q3",
      type: "matching",
      prompt: "Match each hotel with its price per night.",
      items: ["Hotel near the beach", "Hotel in the city centre"],
      options: ["€90", "€100", "€110", "€120"],
      answers: [2, 0],
    },
    {
      id: "q4",
      type: "mcq",
      prompt: "Which hotel do they choose?",
      options: ["The hotel near the beach", "The hotel in the city centre", "Both hotels", "Neither"],
      answer: 1,
    },
    {
      id: "q5",
      type: "note_completion",
      prompt: "Flight time: ____ from Heathrow.",
      wordLimit: 2,
      answer: "10:30",
      acceptable: ["10:30", "ten thirty", "10.30", "1030", "half past ten"],
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "How much do the two return flights cost in total?",
      wordLimit: 2,
      answer: "£320",
      acceptable: ["£320", "320", "320 pounds", "three hundred and twenty pounds", "three hundred twenty"],
    },
    {
      id: "q7",
      type: "mcq",
      prompt: "Do they need a visa for Spain?",
      options: ["Yes", "No", "Only the husband", "Only the wife"],
      answer: 1,
    },
    {
      id: "q8",
      type: "sentence_completion",
      prompt: "Their passport must be valid for at least ____ months.",
      wordLimit: 1,
      answer: "six",
      acceptable: ["six", "6"],
    },
  ],
};

// ---------------------------------------------------------------------------
// SECTION 2 — Short monologues on everyday topics
// ---------------------------------------------------------------------------

const S2_T1: ListeningTest = {
  id: "s2-t1",
  sectionId: 2,
  title: "The local farmers' market",
  description: "A guide tells visitors about the weekly farmers' market.",
  segments: [
    { voice: "nova", text: "Hello everyone, and welcome to our town. I want to tell you about our farmers' market." },
    { voice: "nova", text: "The market is open every Saturday from eight in the morning until two in the afternoon." },
    { voice: "nova", text: "It is held in the main square, right in the centre of the town." },
    { voice: "nova", text: "You can find lots of fresh things here. Local farmers sell vegetables, fruit, cheese, bread and honey." },
    { voice: "nova", text: "The cheese stall is the most popular one. It is run by a family from the next village." },
    { voice: "nova", text: "There is also a small cafe at the market. It serves hot drinks and homemade cakes." },
    { voice: "nova", text: "Most things cost between one and five pounds, so the market is good for your wallet too." },
    { voice: "nova", text: "Please remember to bring a bag with you. We do not give out plastic bags here." },
    { voice: "nova", text: "If you come by car, there is free parking behind the church. It is only a five-minute walk to the square." },
    { voice: "nova", text: "Children love the market too. Every Saturday at eleven, there is a free music show for families." },
    { voice: "nova", text: "I hope you enjoy your visit. If you have any questions, please ask any of the helpers in the green T-shirts." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "When is the market open?",
      options: ["Every day", "Saturday morning only", "Saturday from 8 am to 2 pm", "Sunday all day"],
      answer: 2,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "The market is in the ____ square.",
      wordLimit: 1,
      answer: "main",
      acceptable: ["main"],
    },
    {
      id: "q3",
      type: "matching",
      prompt: "Match each fact with the correct stall or place.",
      items: ["Most popular stall", "Run by a local family", "Plays music for families"],
      options: ["Bread stall", "Cheese stall", "The cafe", "The free music show"],
      answers: [1, 1, 3],
    },
    {
      id: "q4",
      type: "note_completion",
      prompt: "Most prices are between £1 and £____.",
      wordLimit: 1,
      answer: "5",
      acceptable: ["5", "five"],
    },
    {
      id: "q5",
      type: "short_answer",
      prompt: "What must visitors bring with them?",
      wordLimit: 1,
      answer: "bag",
      acceptable: ["bag", "a bag", "bags", "their bag"],
    },
    {
      id: "q6",
      type: "mcq",
      prompt: "Where is the free parking?",
      options: ["In front of the cafe", "Behind the church", "By the river", "Next to the square"],
      answer: 1,
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "The free music show starts at ____.",
      wordLimit: 1,
      answer: "eleven",
      acceptable: ["eleven", "11", "11am", "11 am", "11:00"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "How can you spot a helper?",
      options: ["They wear green T-shirts.", "They wear red caps.", "They carry a clipboard.", "They stand at the entrance."],
      answer: 0,
    },
  ],
};

const S2_T2: ListeningTest = {
  id: "s2-t2",
  sectionId: 2,
  title: "How to use the city library",
  description: "A librarian explains the basic rules of the city library.",
  segments: [
    { voice: "alloy", text: "Welcome to the city library. Let me explain a few simple things before you start." },
    { voice: "alloy", text: "To borrow books, you need a library card. It is free, but you must show some ID, like a passport or a driving licence." },
    { voice: "alloy", text: "You can borrow up to ten books at a time. You can keep them for three weeks." },
    { voice: "alloy", text: "If you keep a book for too long, the fine is twenty pence per day." },
    { voice: "alloy", text: "On the ground floor we have novels and magazines, and on the first floor you will find study books and dictionaries." },
    { voice: "alloy", text: "The children's room is in the basement. There are toys, picture books, and a story time every Wednesday at four." },
    { voice: "alloy", text: "We have computers you can use for free, but please book your time online or at the desk." },
    { voice: "alloy", text: "You can also print pages. Black and white printing is ten pence per page, and colour is fifty pence per page." },
    { voice: "alloy", text: "Please remember to keep quiet inside the building. If you want to talk on the phone, please go outside." },
    { voice: "alloy", text: "The library closes at eight in the evening on weekdays and at five on Saturday. We are closed on Sunday." },
    { voice: "alloy", text: "If you have any other questions, just come to the desk. We are happy to help." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "What do you need to get a library card?",
      options: ["Just your name", "Some ID", "A photo and a fee", "A school letter"],
      answer: 1,
    },
    {
      id: "q2",
      type: "note_completion",
      prompt: "You can borrow up to ____ books at a time.",
      wordLimit: 1,
      answer: "10",
      acceptable: ["10", "ten"],
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "Books can be kept for ____ weeks.",
      wordLimit: 1,
      answer: "three",
      acceptable: ["three", "3"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match the item with where you can find it.",
      items: ["Novels", "Study books", "Children's books"],
      options: ["Ground floor", "First floor", "Basement", "Outside"],
      answers: [0, 1, 2],
    },
    {
      id: "q5",
      type: "short_answer",
      prompt: "How much is the fine per day for a late book?",
      wordLimit: 2,
      answer: "20p",
      acceptable: ["20p", "20 pence", "twenty pence", "20", "£0.20"],
    },
    {
      id: "q6",
      type: "mcq",
      prompt: "When is the children's story time?",
      options: ["Every day", "Wednesday at 4", "Saturday morning", "Friday after school"],
      answer: 1,
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "Colour printing costs ____ pence per page.",
      wordLimit: 1,
      answer: "fifty",
      acceptable: ["fifty", "50"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "When is the library closed?",
      options: ["Sunday", "Saturday", "Wednesday", "Friday evening"],
      answer: 0,
    },
  ],
};

const S2_T3: ListeningTest = {
  id: "s2-t3",
  sectionId: 2,
  title: "A short museum tour",
  description: "A guide gives information at the start of a museum tour.",
  segments: [
    { voice: "nova", text: "Good morning, and welcome to the National History Museum. My name is Lucy, and I will be your guide today." },
    { voice: "nova", text: "Our tour will last about one hour. We will visit three rooms together." },
    { voice: "nova", text: "Please stay close to the group, and do not touch the objects in the glass cases." },
    { voice: "nova", text: "You can take photos, but please do not use a flash. The light can damage the old paintings." },
    { voice: "nova", text: "Our first stop is the dinosaur room on the ground floor. The biggest dinosaur there is fifteen metres long." },
    { voice: "nova", text: "After that, we will go to the Egyptian room on the first floor. It has a real mummy and many gold objects." },
    { voice: "nova", text: "The last room is about modern science. There you can play with simple machines and learn how they work." },
    { voice: "nova", text: "If you get tired, there are benches in every room. There is also a cafe near the main entrance." },
    { voice: "nova", text: "The toilets are next to the cafe, and there is also a small shop where you can buy postcards and books." },
    { voice: "nova", text: "If you lose the group, do not worry. Just go back to the main entrance and wait for me there." },
    { voice: "nova", text: "Right then, please follow me. The dinosaur room is just over here." },
  ],
  questions: [
    {
      id: "q1",
      type: "short_answer",
      prompt: "What is the guide's name?",
      wordLimit: 1,
      answer: "Lucy",
      acceptable: ["lucy"],
    },
    {
      id: "q2",
      type: "mcq",
      prompt: "How long is the tour?",
      options: ["30 minutes", "About 1 hour", "About 2 hours", "Half a day"],
      answer: 1,
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "Visitors can take photos but must not use a ____.",
      wordLimit: 1,
      answer: "flash",
      acceptable: ["flash", "the flash"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each room with what you can see there.",
      items: ["Ground floor room", "First floor room", "Last room"],
      options: ["A real mummy", "A 15-metre dinosaur", "Simple machines", "Old paintings"],
      answers: [1, 0, 2],
    },
    {
      id: "q5",
      type: "note_completion",
      prompt: "The biggest dinosaur is ____ metres long.",
      wordLimit: 1,
      answer: "15",
      acceptable: ["15", "fifteen"],
    },
    {
      id: "q6",
      type: "mcq",
      prompt: "Where is the cafe?",
      options: ["In the basement", "Near the main entrance", "On the top floor", "Next to the dinosaur room"],
      answer: 1,
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "What should you do if you lose the group?",
      wordLimit: 2,
      answer: "go back",
      acceptable: ["go back", "wait", "wait there", "go to the entrance", "go back to the entrance", "return"],
    },
    {
      id: "q8",
      type: "sentence_completion",
      prompt: "There are ____ in every room for tired visitors.",
      wordLimit: 1,
      answer: "benches",
      acceptable: ["benches", "seats"],
    },
  ],
};

const S2_T4: ListeningTest = {
  id: "s2-t4",
  sectionId: 2,
  title: "A weather forecast",
  description: "A short weather forecast for the weekend.",
  segments: [
    { voice: "alloy", text: "Good evening, and here is the weather for the weekend." },
    { voice: "alloy", text: "On Saturday morning, the day will start sunny in most parts of the country." },
    { voice: "alloy", text: "In the south, temperatures will reach about twenty-two degrees by lunchtime." },
    { voice: "alloy", text: "However, in the afternoon, there will be some rain in the north and west. Please take an umbrella with you." },
    { voice: "alloy", text: "On Saturday evening, the rain will move to the south. It may also be windy near the coast." },
    { voice: "alloy", text: "Sunday will be much better. Most of the country will have sunshine and only a few clouds." },
    { voice: "alloy", text: "Sunday is also a good day for the beach, but please remember to use sun cream." },
    { voice: "alloy", text: "The warmest place this weekend will be Brighton, with a high of twenty-six degrees on Sunday afternoon." },
    { voice: "alloy", text: "The coldest place will be Edinburgh, with rain on Saturday and only fourteen degrees." },
    { voice: "alloy", text: "Looking ahead, on Monday the weather will change again, and showers will return to most areas." },
    { voice: "alloy", text: "That was the weekend forecast. Have a lovely weekend, whatever you do." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "How will Saturday start?",
      options: ["Cloudy", "Sunny", "Rainy", "Snowy"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "In the south, temperatures will reach about ____ degrees by lunchtime.",
      wordLimit: 1,
      answer: "22",
      acceptable: ["22", "twenty-two", "twenty two"],
    },
    {
      id: "q3",
      type: "mcq",
      prompt: "Where will it rain on Saturday afternoon?",
      options: ["South only", "East only", "North and west", "Everywhere"],
      answer: 2,
    },
    {
      id: "q4",
      type: "short_answer",
      prompt: "What should people take with them on Saturday?",
      wordLimit: 2,
      answer: "umbrella",
      acceptable: ["umbrella", "an umbrella", "their umbrella"],
    },
    {
      id: "q5",
      type: "matching",
      prompt: "Match the city with its weather.",
      items: ["Brighton", "Edinburgh"],
      options: ["Coldest, with rain", "Warmest, 26°C", "Cloudy all weekend", "Foggy"],
      answers: [1, 0],
    },
    {
      id: "q6",
      type: "note_completion",
      prompt: "Edinburgh: rain on Saturday, only ____ degrees.",
      wordLimit: 1,
      answer: "14",
      acceptable: ["14", "fourteen"],
    },
    {
      id: "q7",
      type: "mcq",
      prompt: "What is the advice for Sunday at the beach?",
      options: ["Go swimming early.", "Use sun cream.", "Stay home.", "Bring a coat."],
      answer: 1,
    },
    {
      id: "q8",
      type: "sentence_completion",
      prompt: "On Monday, ____ will return to most areas.",
      wordLimit: 1,
      answer: "showers",
      acceptable: ["showers", "rain"],
    },
  ],
};

const S2_T5: ListeningTest = {
  id: "s2-t5",
  sectionId: 2,
  title: "School announcement",
  description: "A teacher gives morning announcements at school.",
  segments: [
    { voice: "nova", text: "Good morning, students. I have a few short announcements before lessons begin." },
    { voice: "nova", text: "First, the school trip to the science centre is on Friday. Please remember to bring your packed lunch." },
    { voice: "nova", text: "The bus will leave at half past eight in the morning, sharp. Do not be late." },
    { voice: "nova", text: "If you have not yet paid the ten pounds for the trip, please pay at the office today." },
    { voice: "nova", text: "Second, the football match against Riverside School is on Wednesday afternoon at four." },
    { voice: "nova", text: "Everyone is welcome to come and watch. The match is on the main school field." },
    { voice: "nova", text: "Third, the library will be closed for cleaning on Tuesday morning. It will reopen at one o'clock." },
    { voice: "nova", text: "Finally, please remember that you must not eat or drink in the computer rooms. Water is allowed only in a closed bottle." },
    { voice: "nova", text: "If you find any lost property, please bring it to the main office, not to your teacher." },
    { voice: "nova", text: "That is all for today. Have a great morning, and please leave the hall in a quiet line." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Where is the school trip going?",
      options: ["The history museum", "The science centre", "The art gallery", "The zoo"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "Students must bring their own ____ on the trip.",
      wordLimit: 2,
      answer: "packed lunch",
      acceptable: ["packed lunch", "lunch", "a packed lunch", "a lunch"],
    },
    {
      id: "q3",
      type: "note_completion",
      prompt: "Bus leaves at ____ on Friday morning.",
      wordLimit: 2,
      answer: "8:30",
      acceptable: ["8:30", "half past eight", "eight thirty", "8.30", "0830"],
    },
    {
      id: "q4",
      type: "short_answer",
      prompt: "How much is the trip?",
      wordLimit: 2,
      answer: "£10",
      acceptable: ["£10", "10", "ten pounds", "10 pounds"],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "When is the football match?",
      options: ["Monday at 4", "Wednesday at 4", "Friday at 4", "Saturday morning"],
      answer: 1,
    },
    {
      id: "q6",
      type: "sentence_completion",
      prompt: "On Tuesday morning, the ____ will be closed for cleaning.",
      wordLimit: 1,
      answer: "library",
      acceptable: ["library", "the library"],
    },
    {
      id: "q7",
      type: "mcq",
      prompt: "What can students bring into the computer rooms?",
      options: ["Snacks", "Water in a closed bottle", "Coffee", "Nothing at all"],
      answer: 1,
    },
    {
      id: "q8",
      type: "short_answer",
      prompt: "Where should lost property be taken?",
      wordLimit: 3,
      answer: "main office",
      acceptable: ["main office", "the main office", "office", "the office", "to the office"],
    },
  ],
};

// ---------------------------------------------------------------------------
// SECTION 3 — Conversations in a simple educational context
// ---------------------------------------------------------------------------

const S3_T1: ListeningTest = {
  id: "s3-t1",
  sectionId: 3,
  title: "Choosing a class project",
  description: "Two students and their teacher discuss a class project.",
  segments: [
    { voice: "nova", text: "Okay, Mark and Lisa, have you chosen a topic for your project?" },
    { voice: "alloy", text: "Yes, miss. We want to do something about healthy food." },
    { voice: "nova", text: "That sounds good. What exactly do you want to focus on?" },
    { voice: "nova", text: "Well, we were thinking about school lunches. We want to know if students like them or not." },
    { voice: "alloy", text: "Right. So we will make a short questionnaire and ask thirty students to answer it." },
    { voice: "nova", text: "Good idea. Will you ask only your class, or other classes too?" },
    { voice: "alloy", text: "We will ask three different classes, so the answers are more reliable." },
    { voice: "nova", text: "That is much better. And how will you show your results?" },
    { voice: "nova", text: "We will use a chart and write a short report." },
    { voice: "alloy", text: "Yes, and we will make a poster for the classroom too." },
    { voice: "nova", text: "Excellent. Make sure your report is at least two pages long, but not more than four." },
    { voice: "alloy", text: "Okay. When do we have to hand it in?" },
    { voice: "nova", text: "By Friday next week. Please give it to me before lunchtime." },
    { voice: "alloy", text: "Will you help us if we have problems?" },
    { voice: "nova", text: "Of course. Come to my office on Tuesday afternoon between two and four." },
    { voice: "nova", text: "Thank you, miss. We will start tomorrow." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "What is the project about?",
      options: ["Sport", "Healthy food", "Music at school", "School trips"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "They will ask ____ students in total.",
      wordLimit: 1,
      answer: "thirty",
      acceptable: ["thirty", "30"],
    },
    {
      id: "q3",
      type: "mcq",
      prompt: "How many classes will they ask?",
      options: ["One", "Two", "Three", "Four"],
      answer: 2,
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each format with what they will produce.",
      items: ["Visual showing the data", "Written part", "Item for the classroom"],
      options: ["A chart", "A short report", "A poster", "A video"],
      answers: [0, 1, 2],
    },
    {
      id: "q5",
      type: "note_completion",
      prompt: "The report should be between ____ and four pages long.",
      wordLimit: 1,
      answer: "two",
      acceptable: ["two", "2"],
    },
    {
      id: "q6",
      type: "mcq",
      prompt: "When must the project be handed in?",
      options: ["Friday this week", "Monday next week", "Friday next week", "Two Fridays from now"],
      answer: 2,
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "When can they get help from the teacher?",
      wordLimit: 3,
      answer: "Tuesday afternoon",
      acceptable: ["tuesday afternoon", "tuesday", "on tuesday", "on tuesday afternoon", "between 2 and 4", "tuesday 2 to 4"],
    },
    {
      id: "q8",
      type: "sentence_completion",
      prompt: "They will hand the project in before ____ on Friday.",
      wordLimit: 1,
      answer: "lunchtime",
      acceptable: ["lunchtime", "lunch", "lunch time"],
    },
  ],
};

const S3_T2: ListeningTest = {
  id: "s3-t2",
  sectionId: 3,
  title: "A study group meeting",
  description: "Three classmates plan how to study together for an exam.",
  segments: [
    { voice: "alloy", text: "Right, we have a maths exam in three weeks. We should study together." },
    { voice: "nova", text: "Good idea. How often should we meet?" },
    { voice: "alloy", text: "I think twice a week is enough. Maybe Tuesday and Thursday?" },
    { voice: "alloy", text: "Hi everyone, sorry I am late. Are we choosing days?" },
    { voice: "nova", text: "Yes, Sam. Tuesday and Thursday. After school works for you?" },
    { voice: "alloy", text: "Tuesday is fine, but on Thursday I have football. Can we do Wednesday instead?" },
    { voice: "alloy", text: "Sure, Wednesday is okay. Where shall we meet?" },
    { voice: "nova", text: "What about the school library? It is quiet, and there is free Wi-Fi." },
    { voice: "alloy", text: "Good, but the library closes at five. Two hours is a bit short." },
    { voice: "nova", text: "Then we can meet at my house on Wednesday and at the library on Tuesday." },
    { voice: "alloy", text: "Great. What should we bring?" },
    { voice: "nova", text: "Please bring your textbook, a notebook, and a calculator." },
    { voice: "alloy", text: "Should we share the topics? I am bad at fractions, but good at graphs." },
    { voice: "nova", text: "Yes, let us share. I will explain fractions and you can teach us about graphs." },
    { voice: "alloy", text: "Perfect. I will help with word problems. They are my favourite part." },
    { voice: "nova", text: "Wonderful. See you all on Tuesday at four o'clock at the library." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "When is the maths exam?",
      options: ["Next week", "In two weeks", "In three weeks", "Next month"],
      answer: 2,
    },
    {
      id: "q2",
      type: "matching",
      prompt: "Match each day with the meeting place.",
      items: ["Tuesday", "Wednesday"],
      options: ["School library", "Sam's house", "The other student's house", "The cafe"],
      answers: [0, 2],
    },
    {
      id: "q3",
      type: "mcq",
      prompt: "Why did they change Thursday to Wednesday?",
      options: ["The library is closed.", "Sam plays football on Thursday.", "Wednesday is shorter.", "They all have other classes."],
      answer: 1,
    },
    {
      id: "q4",
      type: "note_completion",
      prompt: "The school library closes at ____.",
      wordLimit: 1,
      answer: "five",
      acceptable: ["five", "5", "5pm", "5 pm", "5:00", "17:00"],
    },
    {
      id: "q5",
      type: "sentence_completion",
      prompt: "They should bring a textbook, a notebook, and a ____.",
      wordLimit: 1,
      answer: "calculator",
      acceptable: ["calculator"],
    },
    {
      id: "q6",
      type: "matching",
      prompt: "Match each student with the topic they will explain.",
      items: ["The student bad at fractions", "The student good at fractions", "The student who likes word problems"],
      options: ["Graphs", "Fractions", "Word problems", "Geometry"],
      answers: [0, 1, 2],
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "Why do they like the library?",
      wordLimit: 3,
      answer: "quiet",
      acceptable: ["quiet", "it is quiet", "free wifi", "free wi-fi", "quiet and free wifi", "quiet free wifi"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "What time will they meet on Tuesday?",
      options: ["3 pm", "4 pm", "5 pm", "6 pm"],
      answer: 1,
    },
  ],
};

const S3_T3: ListeningTest = {
  id: "s3-t3",
  sectionId: 3,
  title: "Talking to the school nurse",
  description: "A student talks to the school nurse about feeling tired.",
  segments: [
    { voice: "nova", text: "Hello, please come in and sit down. What is your name?" },
    { voice: "alloy", text: "Hi, my name is Daniel. I am in year nine." },
    { voice: "nova", text: "Hi, Daniel. Your teacher said you were not feeling well. What is the problem?" },
    { voice: "alloy", text: "I feel tired all the time. I cannot focus in class." },
    { voice: "nova", text: "How long has this been happening?" },
    { voice: "alloy", text: "About two weeks." },
    { voice: "nova", text: "How many hours do you sleep at night?" },
    { voice: "alloy", text: "Maybe five or six. I play games until quite late." },
    { voice: "nova", text: "That is not enough. Children your age need eight or nine hours of sleep." },
    { voice: "nova", text: "What about food? Do you eat breakfast in the morning?" },
    { voice: "alloy", text: "Not really. I usually just have a glass of milk." },
    { voice: "nova", text: "You should eat something, even toast or fruit. Breakfast gives you energy for school." },
    { voice: "alloy", text: "Okay. I will try. What about water?" },
    { voice: "nova", text: "Drink at least six glasses of water during the day. Tiredness is often linked to not drinking enough." },
    { voice: "nova", text: "Try this for one week and come back next Monday at the same time." },
    { voice: "alloy", text: "Okay, thank you. Should I tell my parents?" },
    { voice: "nova", text: "Yes, please share these tips with them. They can help you change your habits at home." },
  ],
  questions: [
    {
      id: "q1",
      type: "short_answer",
      prompt: "What is the student's name?",
      wordLimit: 1,
      answer: "Daniel",
      acceptable: ["daniel"],
    },
    {
      id: "q2",
      type: "mcq",
      prompt: "What is the problem?",
      options: ["Headaches", "Stomach pain", "Feeling tired", "Difficulty hearing"],
      answer: 2,
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "He has had this problem for about ____ weeks.",
      wordLimit: 1,
      answer: "two",
      acceptable: ["two", "2"],
    },
    {
      id: "q4",
      type: "note_completion",
      prompt: "Recommended sleep: ____ to nine hours.",
      wordLimit: 1,
      answer: "eight",
      acceptable: ["eight", "8"],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "What does Daniel usually have for breakfast?",
      options: ["Eggs", "Toast", "Just a glass of milk", "Cereal"],
      answer: 2,
    },
    {
      id: "q6",
      type: "matching",
      prompt: "Match each piece of advice with what to do.",
      items: ["Sleep", "Breakfast", "Water"],
      options: ["At least 6 glasses a day", "Eat something every day", "Sleep 8–9 hours", "Take a multivitamin"],
      answers: [2, 1, 0],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "He should come back next ____ at the same time.",
      wordLimit: 1,
      answer: "Monday",
      acceptable: ["monday"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Why does the nurse want him to talk to his parents?",
      options: ["To get medicine", "So they can help him change his habits", "To tell the doctor", "Because he is too young"],
      answer: 1,
    },
  ],
};

const S3_T4: ListeningTest = {
  id: "s3-t4",
  sectionId: 3,
  title: "Choosing a club at college",
  description: "A new student talks to a tutor about clubs at college.",
  segments: [
    { voice: "nova", text: "Hello, you must be the new student. How can I help?" },
    { voice: "alloy", text: "Hi. I want to join a club, but I am not sure which one." },
    { voice: "nova", text: "Great. We have many clubs. What kind of things do you like?" },
    { voice: "alloy", text: "I like reading and films, and I want to meet new people." },
    { voice: "nova", text: "Then the book club could be perfect. They meet every Monday at five o'clock." },
    { voice: "alloy", text: "How many people usually go?" },
    { voice: "nova", text: "Usually about ten students. They read one short novel together each month." },
    { voice: "alloy", text: "Sounds good. Is there a film club too?" },
    { voice: "nova", text: "Yes. The film club meets on Thursday evenings at six. They watch a film and then talk about it." },
    { voice: "alloy", text: "I like that idea. Do I have to pay?" },
    { voice: "nova", text: "The book club is free, but the film club costs five pounds per term to cover snacks." },
    { voice: "alloy", text: "Okay. And how do I sign up?" },
    { voice: "nova", text: "You can sign up online on the college website. Just go to 'student life' and click on the club name." },
    { voice: "alloy", text: "Great. One more thing. Are there any sports clubs?" },
    { voice: "nova", text: "Yes, we have football, basketball, and swimming. The football club is the largest with about forty members." },
    { voice: "alloy", text: "I will think about football too. Thank you for your help." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Why does the student want to join a club?",
      options: ["To improve grades", "To meet new people", "Because it is required", "To get a discount"],
      answer: 1,
    },
    {
      id: "q2",
      type: "matching",
      prompt: "Match each club with the day or time it meets.",
      items: ["Book club", "Film club"],
      options: ["Monday at 5", "Tuesday at 6", "Thursday at 6", "Friday at 5"],
      answers: [0, 2],
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "The book club reads one short ____ each month.",
      wordLimit: 1,
      answer: "novel",
      acceptable: ["novel", "book"],
    },
    {
      id: "q4",
      type: "note_completion",
      prompt: "Film club fee: £____ per term.",
      wordLimit: 1,
      answer: "5",
      acceptable: ["5", "five"],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "How does the student sign up?",
      options: ["By phone", "By email", "On the college website", "In person at the office"],
      answer: 2,
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "Which is the largest sports club?",
      wordLimit: 1,
      answer: "football",
      acceptable: ["football", "the football club", "soccer"],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "The football club has about ____ members.",
      wordLimit: 1,
      answer: "forty",
      acceptable: ["forty", "40"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Which club is free?",
      options: ["The film club", "The book club", "Both clubs", "Neither club"],
      answer: 1,
    },
  ],
};

const S3_T5: ListeningTest = {
  id: "s3-t5",
  sectionId: 3,
  title: "Asking about a course",
  description: "A student asks an advisor about an evening English course.",
  segments: [
    { voice: "alloy", text: "Hello, I would like some information about your evening English course." },
    { voice: "nova", text: "Of course. Are you a beginner or do you have some English already?" },
    { voice: "alloy", text: "I have some English. I can speak a little, but I want to improve." },
    { voice: "nova", text: "Then I think the pre-intermediate course is best for you." },
    { voice: "alloy", text: "How long is the course?" },
    { voice: "nova", text: "It lasts ten weeks. There is one lesson every week, on Tuesday from six to eight in the evening." },
    { voice: "alloy", text: "Great. How big are the classes?" },
    { voice: "nova", text: "We have small groups, only twelve students per class." },
    { voice: "alloy", text: "Who is the teacher?" },
    { voice: "nova", text: "The teacher is Sarah Williams. She has been teaching English for over fifteen years." },
    { voice: "alloy", text: "How much is the course?" },
    { voice: "nova", text: "It is one hundred and eighty pounds for the full course. Books are not included." },
    { voice: "alloy", text: "How much are the books?" },
    { voice: "nova", text: "The textbook is fifteen pounds. You can buy it from us or from any bookshop." },
    { voice: "alloy", text: "Do you give a certificate at the end?" },
    { voice: "nova", text: "Yes. If you come to at least eight of the ten lessons and pass a small test, you receive a certificate." },
    { voice: "alloy", text: "Sounds great. How can I sign up?" },
    { voice: "nova", text: "Please fill in this form and pay a fifty-pound deposit today. The rest you can pay at the first lesson." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Which course does the advisor recommend?",
      options: ["Beginner", "Pre-intermediate", "Intermediate", "Advanced"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "The course lasts ____ weeks.",
      wordLimit: 1,
      answer: "ten",
      acceptable: ["ten", "10"],
    },
    {
      id: "q3",
      type: "note_completion",
      prompt: "Lesson: Tuesday from ____ to 8 pm.",
      wordLimit: 2,
      answer: "6",
      acceptable: ["6", "six", "6 pm", "6pm", "18:00", "18.00", "1800"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each item with the correct number.",
      items: ["Class size", "Course price (£)", "Textbook price (£)"],
      options: ["12", "180", "15", "8"],
      answers: [0, 1, 2],
    },
    {
      id: "q5",
      type: "short_answer",
      prompt: "What is the teacher's name?",
      wordLimit: 2,
      answer: "Sarah Williams",
      acceptable: ["sarah williams", "sarah", "miss williams", "ms williams", "ms. williams"],
    },
    {
      id: "q6",
      type: "sentence_completion",
      prompt: "She has been teaching English for over ____ years.",
      wordLimit: 1,
      answer: "fifteen",
      acceptable: ["fifteen", "15"],
    },
    {
      id: "q7",
      type: "mcq",
      prompt: "What must students do to get a certificate?",
      options: ["Attend all lessons", "Attend at least 8 lessons and pass a test", "Pay extra", "Write an essay"],
      answer: 1,
    },
    {
      id: "q8",
      type: "note_completion",
      prompt: "Deposit to sign up: £____.",
      wordLimit: 1,
      answer: "50",
      acceptable: ["50", "fifty"],
    },
  ],
};

// ---------------------------------------------------------------------------
// SECTION 4 — Short academic monologues, simplified
// ---------------------------------------------------------------------------

const S4_T1: ListeningTest = {
  id: "s4-t1",
  sectionId: 4,
  title: "An introduction to bees",
  description: "A teacher gives a simple talk about honey bees.",
  segments: [
    { voice: "alloy", text: "Today I want to tell you about an amazing little insect — the honey bee." },
    { voice: "alloy", text: "Honey bees live together in large groups called colonies. A colony can have up to fifty thousand bees." },
    { voice: "alloy", text: "There are three kinds of bees in each colony: the queen, the workers, and the drones." },
    { voice: "alloy", text: "There is only one queen, and her job is to lay eggs. She can lay up to two thousand eggs in one day." },
    { voice: "alloy", text: "The workers are all female. They collect nectar from flowers and bring it back to the hive." },
    { voice: "alloy", text: "Inside the hive, the workers turn the nectar into honey. They use the honey for food in winter." },
    { voice: "alloy", text: "The drones are male. Their main job is to mate with the queen. They do not work or collect food." },
    { voice: "alloy", text: "Bees are very important for nature. They help plants by carrying pollen from one flower to another." },
    { voice: "alloy", text: "Without bees, many fruits and vegetables would not grow well." },
    { voice: "alloy", text: "Sadly, the number of bees in the world is going down. This is mostly because of pollution and the loss of wild flowers." },
    { voice: "alloy", text: "We can help by planting flowers in our gardens and by buying honey from local farmers." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "What is the talk mainly about?",
      options: ["Butterflies", "Honey bees", "Ants", "Wasps"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "A group of bees is called a ____.",
      wordLimit: 1,
      answer: "colony",
      acceptable: ["colony", "a colony"],
    },
    {
      id: "q3",
      type: "note_completion",
      prompt: "A colony can have up to ____ thousand bees.",
      wordLimit: 1,
      answer: "fifty",
      acceptable: ["fifty", "50"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each kind of bee with its job.",
      items: ["Queen", "Workers", "Drones"],
      options: ["Lay eggs", "Collect nectar", "Mate with the queen", "Guard the hive"],
      answers: [0, 1, 2],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "How many eggs can a queen lay in one day?",
      options: ["Up to 200", "Up to 1,000", "Up to 2,000", "Up to 20,000"],
      answer: 2,
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "What do bees carry from flower to flower?",
      wordLimit: 1,
      answer: "pollen",
      acceptable: ["pollen"],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "Bees turn nectar into ____.",
      wordLimit: 1,
      answer: "honey",
      acceptable: ["honey"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Why is the number of bees going down?",
      options: ["Bad weather", "Pollution and loss of flowers", "Other insects", "Cold winters"],
      answer: 1,
    },
  ],
};

const S4_T2: ListeningTest = {
  id: "s4-t2",
  sectionId: 4,
  title: "Water on Earth",
  description: "A short geography talk about where water is found on Earth.",
  segments: [
    { voice: "nova", text: "Today, we will talk about water on our planet, Earth." },
    { voice: "nova", text: "Around seventy percent of Earth's surface is covered by water." },
    { voice: "nova", text: "However, most of this water is salty. It is found in the oceans and the seas." },
    { voice: "nova", text: "Only about three percent of all water on Earth is fresh water that we can drink." },
    { voice: "nova", text: "Most fresh water is frozen in the ice at the North and South Poles." },
    { voice: "nova", text: "Other fresh water is found in rivers, lakes, and underground." },
    { voice: "nova", text: "People need water for many things: drinking, cooking, washing, and growing food." },
    { voice: "nova", text: "An adult should drink about two litres of water every day to stay healthy." },
    { voice: "nova", text: "In some parts of the world, people do not have clean water to drink." },
    { voice: "nova", text: "About one billion people in the world face this problem every day." },
    { voice: "nova", text: "We can save water at home in simple ways, like turning off the tap when we brush our teeth." },
    { voice: "nova", text: "Taking shorter showers also helps, because a five-minute shower uses much less water than a long bath." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "About how much of Earth is covered by water?",
      options: ["50%", "60%", "70%", "90%"],
      answer: 2,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "Most water on Earth is ____.",
      wordLimit: 1,
      answer: "salty",
      acceptable: ["salty", "salt", "salt water", "saltwater"],
    },
    {
      id: "q3",
      type: "note_completion",
      prompt: "Only ____ percent of all water is fresh.",
      wordLimit: 1,
      answer: "three",
      acceptable: ["three", "3", "3%"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each place with what is found there.",
      items: ["The poles", "Rivers and lakes", "Oceans"],
      options: ["Salty water", "Fresh water", "Frozen fresh water", "Hot water"],
      answers: [2, 1, 0],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "How much water should an adult drink each day?",
      options: ["About 1 litre", "About 2 litres", "About 3 litres", "As much as possible"],
      answer: 1,
    },
    {
      id: "q6",
      type: "short_answer",
      prompt: "How many people lack clean drinking water?",
      wordLimit: 2,
      answer: "one billion",
      acceptable: ["one billion", "1 billion", "a billion", "1,000,000,000", "billion"],
    },
    {
      id: "q7",
      type: "sentence_completion",
      prompt: "We can save water by turning off the ____ when we brush our teeth.",
      wordLimit: 1,
      answer: "tap",
      acceptable: ["tap", "the tap", "water"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Which uses less water?",
      options: ["A long bath", "A 5-minute shower", "Washing clothes", "Filling a pool"],
      answer: 1,
    },
  ],
};

const S4_T3: ListeningTest = {
  id: "s4-t3",
  sectionId: 4,
  title: "A short history of the bicycle",
  description: "A simple talk about how the bicycle was invented and changed.",
  segments: [
    { voice: "alloy", text: "Today, I want to tell you about a simple but important invention: the bicycle." },
    { voice: "alloy", text: "The first bicycle was made in Germany in eighteen seventeen. It had no pedals, so people pushed it with their feet." },
    { voice: "alloy", text: "About fifty years later, in eighteen sixty-eight, a French inventor added pedals to the front wheel." },
    { voice: "alloy", text: "This made the bicycle faster, but the front wheel was very large, sometimes over a metre tall, so it was not very safe." },
    { voice: "alloy", text: "In eighteen eighty-five, an English engineer designed the safety bicycle. It had two wheels of the same size and a chain." },
    { voice: "alloy", text: "This is the design that we still use today." },
    { voice: "alloy", text: "Bicycles became very popular at the end of the nineteenth century, especially with women. They gave people new freedom to travel." },
    { voice: "alloy", text: "Today, more than a billion bicycles are used around the world. China is the country that uses bicycles the most." },
    { voice: "alloy", text: "Bicycles are good for our health and good for the planet. Riding does not produce any pollution." },
    { voice: "alloy", text: "Many cities are building special bicycle paths to make cycling safer." },
    { voice: "alloy", text: "If we use the bicycle more often, we can reduce traffic, save money, and stay fit at the same time." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Where was the first bicycle made?",
      options: ["France", "England", "Germany", "Italy"],
      answer: 2,
    },
    {
      id: "q2",
      type: "note_completion",
      prompt: "The first bicycle was made in ____.",
      wordLimit: 1,
      answer: "1817",
      acceptable: ["1817", "eighteen seventeen"],
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "The first bicycle had no ____.",
      wordLimit: 1,
      answer: "pedals",
      acceptable: ["pedals"],
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each year with the change.",
      items: ["1817", "1868", "1885"],
      options: ["A French inventor added pedals to the front wheel.", "The safety bicycle was designed.", "The first bicycle had no pedals.", "Bicycles became electric."],
      answers: [2, 0, 1],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "Why was the bicycle with a big front wheel not safe?",
      options: ["It was slow.", "The wheel was very large.", "It had no brakes.", "It was made of wood."],
      answer: 1,
    },
    {
      id: "q6",
      type: "sentence_completion",
      prompt: "The safety bicycle had two wheels of the same size and a ____.",
      wordLimit: 1,
      answer: "chain",
      acceptable: ["chain", "a chain"],
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "Which country uses bicycles the most today?",
      wordLimit: 1,
      answer: "China",
      acceptable: ["china"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Why is the bicycle good for the planet?",
      options: ["It is cheap.", "It does not produce pollution.", "It is fast.", "It is small."],
      answer: 1,
    },
  ],
};

const S4_T4: ListeningTest = {
  id: "s4-t4",
  sectionId: 4,
  title: "The human brain",
  description: "A teacher gives an introduction to the human brain.",
  segments: [
    { voice: "nova", text: "Today, I want to talk about the most important part of your body: the brain." },
    { voice: "nova", text: "The adult human brain weighs about one and a half kilograms." },
    { voice: "nova", text: "It is not very large, but it controls everything we do. It tells the heart to beat, the lungs to breathe, and the eyes to see." },
    { voice: "nova", text: "The brain has three main parts. The biggest part is called the cerebrum." },
    { voice: "nova", text: "It helps us think, remember, and solve problems. It also helps us speak and understand language." },
    { voice: "nova", text: "The second part is called the cerebellum. It is at the back of the brain and it helps us balance and move." },
    { voice: "nova", text: "The third part is called the brainstem. It connects the brain to the spinal cord and it controls things like breathing and heart rate." },
    { voice: "nova", text: "The brain uses a lot of energy. About twenty percent of the food we eat goes to feed the brain." },
    { voice: "nova", text: "Sleep is very important for the brain. While we sleep, the brain saves new information from the day." },
    { voice: "nova", text: "Children need about nine hours of sleep, while adults need around seven or eight." },
    { voice: "nova", text: "Doing puzzles, reading, and learning new things helps to keep the brain strong, even when we are old." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "About how much does the adult brain weigh?",
      options: ["0.5 kg", "1 kg", "1.5 kg", "3 kg"],
      answer: 2,
    },
    {
      id: "q2",
      type: "matching",
      prompt: "Match each part of the brain with its job.",
      items: ["Cerebrum", "Cerebellum", "Brainstem"],
      options: ["Helps with balance and movement", "Controls breathing and heart rate", "Helps with thinking and language", "Stores blood"],
      answers: [2, 0, 1],
    },
    {
      id: "q3",
      type: "sentence_completion",
      prompt: "The cerebellum is at the ____ of the brain.",
      wordLimit: 1,
      answer: "back",
      acceptable: ["back", "the back"],
    },
    {
      id: "q4",
      type: "note_completion",
      prompt: "About ____ percent of the food we eat feeds the brain.",
      wordLimit: 1,
      answer: "twenty",
      acceptable: ["twenty", "20", "20%"],
    },
    {
      id: "q5",
      type: "mcq",
      prompt: "Why is sleep important for the brain?",
      options: ["It cools the brain.", "The brain saves new information.", "It washes the brain.", "The brain grows during sleep."],
      answer: 1,
    },
    {
      id: "q6",
      type: "sentence_completion",
      prompt: "Children need about ____ hours of sleep.",
      wordLimit: 1,
      answer: "nine",
      acceptable: ["nine", "9"],
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "Name one activity that keeps the brain strong.",
      wordLimit: 2,
      answer: "puzzles",
      acceptable: ["puzzles", "doing puzzles", "reading", "learning", "learning new things", "puzzles and reading"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "What does the brainstem connect the brain to?",
      options: ["The heart", "The spinal cord", "The lungs", "The eyes"],
      answer: 1,
    },
  ],
};

const S4_T5: ListeningTest = {
  id: "s4-t5",
  sectionId: 4,
  title: "The story of chocolate",
  description: "A short academic talk about the history of chocolate.",
  segments: [
    { voice: "alloy", text: "Today, I want to tell you a sweet story — the story of chocolate." },
    { voice: "alloy", text: "Chocolate comes from the seeds of the cacao tree. The tree grows in hot countries near the equator." },
    { voice: "alloy", text: "It was first used by the Maya people in Central America more than three thousand years ago." },
    { voice: "alloy", text: "In those days, chocolate was not eaten. It was a bitter drink, mixed with water and spices." },
    { voice: "alloy", text: "The Maya and later the Aztecs believed that chocolate was a gift from the gods." },
    { voice: "alloy", text: "The Spanish brought chocolate to Europe in the sixteenth century." },
    { voice: "alloy", text: "In Europe, people added sugar to make the drink sweet, and it quickly became popular." },
    { voice: "alloy", text: "Solid chocolate, the kind we eat today, was invented in eighteen forty-seven by an English company." },
    { voice: "alloy", text: "Milk chocolate came later, in eighteen seventy-five, in Switzerland." },
    { voice: "alloy", text: "Today, the world produces about five million tons of chocolate every year." },
    { voice: "alloy", text: "The biggest producer of cacao is Ivory Coast in Africa." },
    { voice: "alloy", text: "Chocolate, especially dark chocolate, contains some healthy things, but it is also high in sugar, so we should eat it in small amounts." },
  ],
  questions: [
    {
      id: "q1",
      type: "mcq",
      prompt: "Where does chocolate come from?",
      options: ["The cacao flower", "The seeds of the cacao tree", "Sugar plants", "Coffee beans"],
      answer: 1,
    },
    {
      id: "q2",
      type: "sentence_completion",
      prompt: "Chocolate was first used by the ____ people.",
      wordLimit: 1,
      answer: "Maya",
      acceptable: ["maya", "mayan", "mayans"],
    },
    {
      id: "q3",
      type: "mcq",
      prompt: "How was chocolate first used?",
      options: ["As a sweet bar", "As a bitter drink", "As medicine", "As candy"],
      answer: 1,
    },
    {
      id: "q4",
      type: "matching",
      prompt: "Match each year with what happened.",
      items: ["16th century", "1847", "1875"],
      options: ["Solid chocolate was invented.", "Milk chocolate was invented.", "Chocolate came to Europe.", "Cacao trees were first planted."],
      answers: [2, 0, 1],
    },
    {
      id: "q5",
      type: "note_completion",
      prompt: "Solid chocolate was invented in ____ by an English company.",
      wordLimit: 1,
      answer: "1847",
      acceptable: ["1847", "eighteen forty-seven", "eighteen forty seven"],
    },
    {
      id: "q6",
      type: "sentence_completion",
      prompt: "Milk chocolate was invented in ____.",
      wordLimit: 1,
      answer: "Switzerland",
      acceptable: ["switzerland"],
    },
    {
      id: "q7",
      type: "short_answer",
      prompt: "Which country produces the most cacao today?",
      wordLimit: 2,
      answer: "Ivory Coast",
      acceptable: ["ivory coast", "the ivory coast", "côte d'ivoire", "cote d'ivoire", "cote divoire"],
    },
    {
      id: "q8",
      type: "mcq",
      prompt: "Why should we eat chocolate in small amounts?",
      options: ["It is expensive.", "It is high in sugar.", "It contains caffeine.", "It is hard to find."],
      answer: 1,
    },
  ],
};

export const TESTS: ListeningTest[] = [
  S1_T1, S1_T2, S1_T3, S1_T4, S1_T5,
  S2_T1, S2_T2, S2_T3, S2_T4, S2_T5,
  S3_T1, S3_T2, S3_T3, S3_T4, S3_T5,
  S4_T1, S4_T2, S4_T3, S4_T4, S4_T5,
];

export function getTestById(id: string): ListeningTest | undefined {
  return TESTS.find((t) => t.id === id);
}

export function listTestsForSection(sectionId: number): ListeningTest[] {
  return TESTS.filter((t) => t.sectionId === sectionId);
}
